# Generated by Django 5.2 on 2025-05-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='categoria',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=1),
            preserve_default=False,
        ),
    ]
