# Generated by Django 5.2 on 2025-05-07 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_equipo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vocalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbitro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.arbitro')),
                ('equipo_vocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocalias_asignadas', to='api.equipo')),
                ('jugadores_local_inicial', models.ManyToManyField(related_name='vocalia_local_inicial', to='api.jugador')),
                ('jugadores_visitante_inicial', models.ManyToManyField(related_name='vocalia_visitante_inicial', to='api.jugador')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vocalia', to='api.partido')),
            ],
        ),
    ]
