# Generated by Django 5.2 on 2025-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_jugador_amarillas_acumuladas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='cambios_local',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partido',
            name='cambios_visitante',
            field=models.IntegerField(default=0),
        ),
    ]
